name: Setup GCP Docker Buildx
description: Setup GCP Docker Buildx

inputs:
  gcp_artifact_project_number:
    description: GCP Artifact Project Number
    required: true
  gcp_artifact_project_id:
    description: GCP Artifact Project ID
    required: true
  gcp_artifact_registry_region:
    description: GCP Artifact Registry Region
    required: true
  gcp_artifact_repo_name:
    description: GCP Artifact Repository Name
    required: true
  image_suffix:
    description: Suffix for the image tag. Should be in the format of ".<arch>" (e.g., ".arm64", ".amd64"). If the suffix includes "-native" (e.g., ".arm64-native"), it will set RUSTFLAGS to "-C target-cpu=native".

outputs:
  rise_image_tags:
    description: Docker image tags for rise images
    value: ${{ steps.meta.outputs.tags }}
  rise_image_labels:
    description: Docker image labels for rise images
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: "composite"
  steps:
    - name: Authenticate with Workload Identity Federation
      id: auth
      uses: google-github-actions/auth@v2
      with:
        # Configure the Workload Identity Federation provider and service account to use for authentication
        # Following the instructions at https://github.com/risechain/devops/blob/11909e83f320cac9f747ddddf84f5b8128bca933/docs/docker-image-deployment.md#2-connect-github-actions-to-google-cloud
        workload_identity_provider: "projects/${{ inputs.gcp_artifact_project_number }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
        service_account: "sa-rise-github-actions@${{ inputs.gcp_artifact_project_id }}.iam.gserviceaccount.com"
        token_format: "access_token"

    - name: Authenticate Docker to GCP Artifact Registry
      shell: bash
      run: |
        echo "${{ steps.auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ inputs.gcp_artifact_registry_region }}-docker.pkg.dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create persistent builder
      shell: bash
      run: |
        # Create builder `risebuilder` with `docker-container` driver for multi-arch builds
        docker buildx create --name risebuilder --use --driver docker-container || echo "builder already exists"
        docker buildx inspect risebuilder --bootstrap

    - name: Set up tags and labels for Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.gcp_artifact_registry_region }}-docker.pkg.dev/${{ inputs.gcp_artifact_project_id }}/${{ inputs.gcp_artifact_repo_name }}
        flavor: suffix=${{ inputs.image_suffix }}
        tags: type=sha

    - name: Local cache for docker buildx
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-
